info:
  app:
    name: Farmacia API's
    description: API que permite controlar informações da base de dados de uma farmácia através de métodos Rest HTTP
    version: 1.0.0

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/Farmacia
    username: sa
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
