info:
  app:
    name: Farmacia API's
    description: API que permite controlar informações da base de dados de uma farmácia através de métodos Rest HTTP
    version: 1.0.0

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://${database_url}
    username: ${database_username}
    password: ${database_password}
  jpa:
    hibernate:
      type: trace
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  config:
        import: optional:file:variables.env[.properties]
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
