info:
  app:
    name: Farmacia API's
    description: API que permite controlar informações da base de dados de uma farmácia através de métodos Rest HTTP
    version: 1.0.0

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      type: trace
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public

#
  sql:
    init:
      mode: always
  config:
        import: optional:file:variables.env[.properties]

server:
  port: 5000
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE